import { defineConfig } from 'orval';

// The committed snapshot is the contract: the backend's OpenApiSnapshotTest keeps it equal to the live spec.
// OPENAPI_SPEC points a local run at a spec that is not committed yet.
const input = process.env.OPENAPI_SPEC ?? '../app/src/test/resources/openapi-snapshot.json';

const header = (info: { title?: string; version?: string }) => [
  `${info.title ?? 'API'} client, generated by orval from the committed OpenAPI snapshot. Do not edit.`,
];

export default defineConfig({
  client: {
    input,
    output: {
      mode: 'tags-split',
      target: 'src/generated/endpoints',
      schemas: 'src/generated/model',
      client: 'react-query',
      httpClient: 'fetch',
      mock: {
        generators: [
          { type: 'faker', useExamples: true },
          { type: 'msw', delay: false, useExamples: true },
        ],
      },
      clean: true,
      indexFiles: false,
      override: {
        header,
        mutator: { path: './src/runtime/fetcher.ts', name: 'apiFetch' },
        fetch: { includeHttpResponseReturnType: false },
      },
    },
  },
  zod: {
    input,
    output: {
      mode: 'tags-split',
      target: 'src/generated/zod',
      client: 'zod',
      fileExtension: '.zod.ts',
      clean: true,
      indexFiles: false,
      override: { header },
    },
  },
});
