// Orval is run with indexFiles:false so every generated import carries a Node-ESM `.js` extension;
// this writes the three barrels the package entry points re-export.
import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const generated = fileURLToPath(new URL('../src/generated/', import.meta.url));

const filesUnder = (dir) =>
  readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => (entry.isDirectory() ? filesUnder(join(dir, entry.name)) : [join(dir, entry.name)]))
    .sort();

const exportsOf = (files) =>
  files
    .map((file) => relative(generated, file).split(sep).join('/').replace(/\.ts$/, '.js'))
    .map((path) => `export * from './${path}';`)
    .join('\n');

const write = (name, files) =>
  writeFileSync(join(generated, name), `// Generated by scripts/generate-barrels.mjs - do not edit.\n${exportsOf(files)}\n`);

const endpoints = filesUnder(join(generated, 'endpoints'));
const isMock = (file) => file.endsWith('.msw.ts') || file.endsWith('.faker.ts');

write('index.ts', [...filesUnder(join(generated, 'model')), ...endpoints.filter((file) => !isMock(file))]);
write('mocks.ts', endpoints.filter(isMock));
write('zod.ts', filesUnder(join(generated, 'zod')));
